name: swfc

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - openpyxl
  - jupyter
  - ipykernel
  - pip
  - pip:
      - xgboost
      - shap