"""Final numerical audit: every load-bearing number in main.tex against numbers.json."""
import json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
N = json.load(open(os.path.join(HERE, "numbers.json")))
TEX = open(os.path.join(HERE, "..", "manuscript", "main.tex")).read()
H, R, W, P, C, B, L, O = (N["headroom"], N["resolved"], N["winner_counts"], N["pareto"],
                          N["criteria"], N["boundary"], N["ladder"], N["ood"])
LAD = {r["selector"]: r for r in L["ladder"]}

CHECKS = []
def chk(label, string, expected=None):
    """`string` must appear in the manuscript; `expected` is the recomputed value
    it is asserted to represent, for the record."""
    CHECKS.append((label, string, string in TEX, expected))

# campaign and ledger
chk("main runs", "12{,}960", N["totals"]["main_campaign_runs"])
chk("attempted", "20{,}284", N["totals"]["attempted_runs"])
chk("succeeded", "18{,}124", N["totals"]["successful_runs"])
chk("failed bypass", "2{,}160", N["totals"]["failed_runs"])
chk("contexts", "648", N["campaign"]["n_contexts"])
chk("completion", "1.0000", N["campaign"]["min_completion"])
chk("vehicles", "22.0 million", N["campaign"]["n_vehicles_total"])
chk("boundary runs", "1{,}140", 1140)
chk("sens runs", "1{,}920", 1920)
chk("o8 runs", "1{,}080", 1080)

# complementarity
chk("resolved P3", "P3 227", R["counts"]["P3"])
chk("resolved P4", "P4 19", R["counts"]["P4"])
chk("resolved P1", "P1 11", R["counts"]["P1"])
chk("n resolved", "257 of 648", R["n_resolved"])
chk("n unresolved", "391", R["n_unresolved"])
chk("frac unresolved", "60.3", 100 * R["n_unresolved"] / 648)
chk("median resolved margin", "5.20", R["median_resolved_margin_pct"])
chk("median unresolved margin", "0.13", R["median_unresolved_margin_pct"])
chk("max resolved margin", "26.9", R["max_resolved_margin_pct"])
chk("ties", "50 of 648", N["ties"]["n_tied"])
chk("tie pct", "7.7", 100 * N["ties"]["frac_tied"])
chk("tie P2P4", "39", N["ties"]["composition"]["P2+P4"])
chk("winner P3", "P3 418", W["stable_tiebreak"]["P3"])
chk("winner unique P3", "P3 415", W["unique_minimum_only"]["P3"])
chk("unique min", "598", W["n_unique_minimum"])
chk("ident P2P4", "42.6", 100 * N["operational_identity"]["P2-P4"])
chk("ident P2P3", "22.7", 100 * N["operational_identity"]["P2-P3"])
chk("ident P3P4", "20.2", 100 * N["operational_identity"]["P3-P4"])
chk("mean ident", "14.2", 100 * N["mean_operational_identity"])
chk("map constant", "64.5", 100 * N["winner_map"]["constant"])
chk("map demand", "66.5", 100 * N["winner_map"]["best_single_rate"])
chk("map two", "70.7", 100 * N["winner_map"]["best_two_rate"])
chk("map three", "79.2", 100 * N["winner_map"]["best_three_rate"])

# headroom / decision value
chk("sbs cost", "474.35", H["cost_sbs"])
chk("vbs cost", "473.90", H["cost_vbs"])
chk("headroom", "0.45", H["headroom_s"])
chk("headroom pct", "0.095", H["headroom_pct_aggregate"])
chk("headroom pct ctx", "0.120", H["headroom_pct_per_context"])
chk("P1 penalty", "220.21", H["penalty_s"]["P1"])
chk("P1 pct", "46.4", H["penalty_pct"]["P1"])
chk("P2 penalty", "16.34", H["penalty_s"]["P2"])
chk("P4 penalty", "18.34", H["penalty_s"]["P4"])
chk("P1 cost", "694.56", H["mean_cost"]["P1"])
chk("P2 cost", "490.69", H["mean_cost"]["P2"])
chk("P4 cost", "492.69", H["mean_cost"]["P4"])
chk("sbs attains min", "426 of 648", H["n_sbs_attains_min"])
chk("frac attains", "65.7", 100 * H["frac_sbs_attains_min"])
chk("n not best", "222", H["n_sbs_not_best"])
chk("loss when not best", "1.32", H["mean_loss_when_not_best"])
chk("margin when best", "22.47", H["mean_margin_when_best"])
chk("max headroom", "17.19", H["max_headroom_s"])
chk("resolvable", "55 of the 222", N["resolvability"]["n_headroom_exceeds_noise"])
chk("resolvable pct", "24.8", 100 * N["resolvability"]["frac_headroom_exceeds_noise"])
chk("noise band nonzero", "1.67", N["resolvability"]["mean_noise_2se_where_nonzero_s"])
chk("seeds needed", "25 seeds", N["resolvability"]["seeds_for_mean_effect"])
chk("runs needed", "64{,}800", 64800)
chk("noise floor", "20.90", N["resolvability"]["mean_noise_floor_s"])

# selector ladder
chk("B1 regret", "0.773", LAD["B1_mechanistic"]["mean_regret"])
chk("B0 regret", "0.451", LAD["B0_SBS"]["mean_regret"])
chk("B2 regret", "0.343", LAD["B2_tree3"]["mean_regret"])
chk("B3 regret", "0.282", LAD["B3_logit"]["mean_regret"])
chk("B4 regret", "0.199", LAD["B4_GBDT"]["mean_regret"])
chk("B4 gap", "55.8", 100 * LAD["B4_GBDT"]["gap_closed_vs_SBS"])
chk("B3 gap", "37.4", 100 * LAD["B3_logit"]["gap_closed_vs_SBS"])
chk("B2 gap", "23.8", 100 * LAD["B2_tree3"]["gap_closed_vs_SBS"])
chk("B1 top1", "66.7", 100 * L["top1"]["B1_mechanistic"])
chk("B0 top1", "64.5", 100 * L["top1"]["B0_SBS"])
chk("B3 top1", "76.1", 100 * L["top1"]["B3_logit"])
chk("B4 top1", "73.1", 100 * L["top1"]["B4_GBDT"])
chk("B4 max", "6.96", LAD["B4_GBDT"]["max_regret"])
chk("B0 max", "17.19", LAD["B0_SBS"]["max_regret"])
chk("B4 cvar", "1.66", LAD["B4_GBDT"]["cvar90"])
chk("B0 cvar", "3.67", LAD["B0_SBS"]["cvar90"])
chk("B1 cvar", "6.47", LAD["B1_mechanistic"]["cvar90"])
chk("B4 deviates", "233 of 648", L["b4_deviates_from_sbs"])
chk("B4 saving", "0.25", 0.2515)
chk("B4 saving pct", "0.053", 0.053)
chk("B4 new cost", "474.10", LAD["B4_GBDT"]["mean_cost"])

# criteria
chk("pareto nonsingleton", "73.0", 100 * P["frac_non_singleton"])
chk("pareto n", "473 of 648", 648 - P["sizes"]["1"])
chk("pareto mean size", "2.11", P["mean_size"])
chk("P3 pareto", "555", P["membership"]["P3"])
chk("P4 pareto", "525", P["membership"]["P4"])
chk("P2 pareto", "266", P["membership"]["P2"])
chk("P4 on C3", "429", N["best_by_criterion"]["C3"]["P4"])
chk("P4 on C1", "129", N["best_by_criterion"]["C1"]["P4"])
chk("P4 on C2", "128", N["best_by_criterion"]["C2"]["P4"])
chk("within C1C2", "0.80", C["C1_C2"]["within"])
chk("within C1C3", "0.60", C["C1_C3"]["within"])
chk("within C2C3", "0.65", C["C2_C3"]["within"])
chk("pooled C1C2", "0.94", C["C1_C2"]["pooled"])
chk("C2 differs", "192", 192)
chk("C3 differs", "363", 363)
chk("identical order C1C2", "52.2", 100 * C["C1_C2"]["n_identical_order"] / 648)

# shift
for k, v in (("O1", "0.983"), ("O2", "0.531"), ("O3", "0.167"), ("O7", "2.216"), ("O8", "0.176")):
    chk(f"{k} B4", v, O[{"O1": "O1_demand_high", "O2": "O2_demand_low", "O3": "O3_demand_mid",
                         "O7": "O7_incident", "O8": "O8_northcorridor"}[k]]["B4_GBDT"]["mean_regret"])
chk("O7 B0", "0.630", O["O7_incident"]["B0_SBS"]["mean_regret"])
chk("O6 B4", "1.157", O["O6_green_high"]["B4_GBDT"]["mean_regret"])
chk("abstention", "233", 233)
chk("O8 flagged none", "0\\,\\%", 0.0)

# sensitivity and boundary
PS = N["parameter_sensitivity"]
chk("p3 eps 0.3", "16.66", PS["P3"]["alternatives"]["0.3"]["mean_change_s"])
chk("p3 eps 0.1", "8.10", PS["P3"]["alternatives"]["0.1"]["mean_change_s"])
chk("p4 lam 1.5", "1.27", PS["P4"]["alternatives"]["1.5"]["mean_change_s"])
chk("p4 lam 0.5", "0.11", PS["P4"]["alternatives"]["0.5"]["mean_change_s"])
chk("pref changes", "14.5", 100 * N["preference_sensitivity"]["frac_profile_changes_decision"])
chk("pref TIME", "92.9", 100 * N["preference_sensitivity"]["frac_profile_agrees_with_C1"]["TIME"])
chk("pref BAL", "86.0", 100 * N["preference_sensitivity"]["frac_profile_agrees_with_C1"]["BALANCED"])
chk("pref ENV", "80.1", 100 * N["preference_sensitivity"]["frac_profile_agrees_with_C1"]["ENVIRONMENT"])
chk("boundary n", "Nineteen", B["n_transitions"])
chk("boundary monotone", "Thirteen", B["n_monotone"])
chk("boundary 150", "150\\,veh/h", B["refinement_step"])
chk("boundary resolved ends", "seven", B["n_with_resolved_endpoint"])
chk("ratio 490", "490", 488.4)
chk("ratio 37", "37", 36.9)
chk("upside ratio", "17", H["upside_downside_ratio"])

bad = [c for c in CHECKS if not c[2]]
print(f"MANUSCRIPT NUMERICAL AUDIT")
print(f"  load-bearing numbers checked : {len(CHECKS)}")
print(f"  matched                      : {len(CHECKS)-len(bad)}")
print(f"  not found in manuscript      : {len(bad)}")
for lab, s, _, exp in bad:
    print(f"    MISSING  {lab}: expected string {s!r} (recomputed value {exp})")
sys.exit(1 if bad else 0)
