#!/usr/bin/env python3
"""Regenerate the manuscript's numerical tables from the frozen artefacts.

Emits LaTeX and CSV under outputs/paper/tables/. The manuscripts keep their
tables inline so each .tex stays self-contained for submission; these files are
the machine-checkable counterpart, and
``verify_frozen_manuscript_numbers.py`` independently confirms that the inline
literals agree with the same frozen sources.

Scientific contract
-------------------
* Reads frozen artefacts; writes only under outputs/paper/.
* Performs no aggregation beyond formatting values that were already frozen,
  and the two count columns (positive worlds, constancy) which are simple
  tallies over frozen per-world booleans.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import _frozen as fz  # noqa: E402

DISPLAY = {
    "OracleAttribution": "Oracle attribution",
    "SHAP": "SHAP",
    "PermutationImportance": "Permutation importance",
    "RidgePlus": "Ridge+",
    "CRITIC": "CRITIC",
    "Entropy": "Entropy",
}


def _z(value: float, fmt: str) -> str:
    """Format, normalising a negative zero to a plain zero."""
    out = format(value, fmt)
    return format(0.0, fmt) if float(out) == 0 else out


def table_contrasts(outdir: Path) -> None:
    a = fz.pilot_b_assessments()
    rows = []
    for key, label in DISPLAY.items():
        e = a[key]
        rows.append({
            "method": label,
            "mw_dtop1": _z(e["modal_top1_median_advantage"], ".3f"),
            "mw_dtop1_positive_worlds": e["modal_top1_positive_seed_count"],
            "mw_dregret": _z(e["modal_regret_median_advantage"], ".6f"),
            "mw_dregret_positive_worlds": e["modal_regret_positive_seed_count"],
            "rw_dtau_b": _z(e["random_kendall_median_advantage"], ".3f"),
            "rw_dtau_b_positive_worlds": e["random_kendall_positive_seed_count"],
            "rw_dregret": _z(e["random_regret_median_advantage"], ".6f"),
            "rw_dregret_positive_worlds": e["random_regret_positive_seed_count"],
            "separates_random": "Yes" if e["separates_random"] else "No",
            "escapes_majority_winner": "Yes" if e["escapes_majority_winner"] else "No",
        })
    _write_csv(outdir / "pilot_b_contrasts.csv", rows)

    lines = [
        "% Generated by scripts/paper/build_pilot_b_tables.py from the frozen",
        "% Pilot-B result. Do not edit by hand.",
        r"\begin{tabular}{@{}lrrrrc@{}}", r"\toprule",
        r"Method & \shortstack{MW\\$\Delta$Top-1 (P)} & \shortstack{MW\\$\Delta$regret (P)} &",
        r"\shortstack{RW\\$\Delta\tau_b$ (P)} & \shortstack{RW\\$\Delta$regret (P)} & RW sep.\\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            f"{r['method']} & ${r['mw_dtop1']}$ ({r['mw_dtop1_positive_worlds']}) & "
            f"${r['mw_dregret']}$ ({r['mw_dregret_positive_worlds']}) & "
            f"${r['rw_dtau_b']}$ ({r['rw_dtau_b_positive_worlds']}) & "
            f"${r['rw_dregret']}$ ({r['rw_dregret_positive_worlds']}) & "
            f"{r['separates_random']}\\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write_text(outdir / "pilot_b_contrasts.tex", "\n".join(lines) + "\n")


def table_gate(outdir: Path) -> None:
    d = fz.load_json(fz.PILOT_B)
    hse = d["hard_stop_evaluation"]
    g = hse["gates"]
    a = fz.pilot_b_assessments()
    ows = hse["oracle_winner_summary"]
    ris = hse["random_context_invariance_summary"]
    eligible = sum(1 for e in a.values() if e["eligible"])
    separated = sum(1 for e in a.values() if e["separates_random"])
    escaped = sum(1 for e in a.values() if e["escapes_majority_winner"])
    rows = [
        {"gate": "Coverage",
         "audited_result": f"{eligible} structured methods eligible without fallback",
         "stop": g["coverage_hard_stop"]},
        {"gate": "Random equivalence",
         "audited_result": f"{separated} of 6 methods separated from RandomWeights",
         "stop": g["random_equivalence_hard_stop"]},
        {"gate": "Modal-winner tie",
         "audited_result": f"{escaped} of 6 methods escaped MajorityWinner",
         "stop": g["modal_winner_effective_tie_hard_stop"]},
        {"gate": "Oracle dominance",
         "audited_result": f"Pooled modal share {ows['pooled_modal_winner_share']:.3f} < 0.90",
         "stop": g["oracle_winner_dominance_hard_stop"]},
        {"gate": "Weight insensitivity",
         "audited_result": (f"Invariant fraction {ris['pooled_invariant_fraction']:.3f} < 0.90; "
                            f"qualified worlds {ris['performance_width_seed_count']} < 4"),
         "stop": g["weight_insensitivity_hard_stop"]},
        {"gate": "Overall (OR)",
         "audited_result": "At least one prospectively frozen stop fired",
         "stop": hse["hard_stop"]},
    ]
    _write_csv(outdir / "pilot_b_gate_outcome.csv", rows)
    lines = ["% Generated from the frozen Pilot-B result. Do not edit by hand.",
             r"\begin{tabularx}{\linewidth}{@{}lXc@{}}", r"\toprule",
             r"Gate & Audited result & Stop\\", r"\midrule"]
    for i, r in enumerate(rows):
        if i == len(rows) - 1:
            lines.append(r"\midrule")
        mark = r"\textbf{Yes}" if r["stop"] else "No"
        lines.append(f"{r['gate']} & {r['audited_result']} & {mark}\\\\")
    lines += [r"\bottomrule", r"\end{tabularx}"]
    _write_text(outdir / "pilot_b_gate_outcome.tex", "\n".join(lines) + "\n")


def table_d29(outdir: Path) -> None:
    rows = []
    for r in fz.load_csv(fz.D29_LAYER_B_CSV):
        rows.append({
            "world": r["replication_seed"],
            "distinct_orderings": r["distinct_complete_oracle_orderings"],
            "distinct_winners": r["distinct_deterministic_oracle_winners"],
            "modal_winner": r["modal_oracle_winner_id"],
            "modal_share": f"{float(r['modal_oracle_winner_share']):.3f}",
            "mean_normalized_regret":
                f"{float(r['modal_baseline_mean_normalized_oracle_regret']):.8f}",
            "p95_normalized_regret":
                f"{float(r['modal_baseline_p95_normalized_oracle_regret']):.8f}",
        })
    _write_csv(outdir / "d29_decision_geometry.csv", rows)


def table_selection_maps(outdir: Path) -> None:
    s = fz.selection_summaries()
    methods = fz.METHODS + ["Equal"]
    rows = []
    for m in methods:
        const = sum(1 for w in fz.WORLDS
                    if s[(w, m)]["selection_constant_across_200_contexts"])
        mw = sum(1 for w in fz.WORLDS
                 if s[(w, m)]["agreement_with_majority_winner_all_200_contexts"])
        row = {"method": DISPLAY.get(m, m),
               "constant_selection_worlds": f"{const}/5",
               "all_context_mw_match_worlds": f"{mw}/5"}
        for w in fz.WORLDS:
            e = s[(w, m)]
            row[f"w{w}"] = (f"{e['modal_selected_alternative_id']}/"
                            f"{e['modal_selected_share']:.3f}/"
                            f"{e['number_of_unique_selected_alternatives']}")
        rows.append(row)
    _write_csv(outdir / "post_closure_selection_maps.csv", rows)

    lines = ["% Generated from the frozen post-closure selection-map artefact.",
             "% Descriptive, non-confirmatory. Do not edit by hand.",
             r"\begin{tabular}{@{}lcc@{}}", r"\toprule",
             r"Method & Constant-selection worlds & All-context MW-match worlds\\",
             r"\midrule"]
    for r in rows:
        lines.append(f"{r['method']} & {r['constant_selection_worlds']} & "
                     f"{r['all_context_mw_match_worlds']}\\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write_text(outdir / "post_closure_selection_maps.tex", "\n".join(lines) + "\n")


def table_per_world_advantages(outdir: Path) -> None:
    a = fz.pilot_b_assessments()
    rows = []
    for w in fz.WORLDS:
        row = {"world": w}
        for m in ("OracleAttribution", "SHAP"):
            row[f"{m}_dTop1"] = _z(a[m]["modal_top1_advantages_by_seed"][str(w)], ".3f")
            row[f"{m}_dregret"] = _z(
                a[m]["modal_regret_advantages_by_seed"][str(w)], ".6f")
        rows.append(row)
    _write_csv(outdir / "per_world_oracle_shap_vs_mw.csv", rows)


def _write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    with fz.open_output(path, newline="") as handle:
        # csv defaults to CRLF; force LF so the files are clean in a Unix repo.
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]),
                                lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {path.relative_to(fz.REPO_ROOT)}")


def _write_text(path: Path, text: str) -> None:
    with fz.open_output(path) as handle:
        handle.write(text)
    print(f"wrote {path.relative_to(fz.REPO_ROOT)}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--outdir", type=Path, default=fz.OUTPUT_ROOT / "tables")
    args = ap.parse_args()
    outdir = Path(fz.guard_output_path(args.outdir))
    table_contrasts(outdir)
    table_gate(outdir)
    table_d29(outdir)
    table_selection_maps(outdir)
    table_per_world_advantages(outdir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
